package com.poc.dao.factory;

import org.jooq.DSLContext;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;

	public class RecordFactory<T, 
	TRECORD extends org.jooq.impl.UpdatableRecordImpl<TRECORD>
	,TTABLE extends org.jooq.impl.TableImpl<TRECORD>> {
		@Autowired
		private DSLContext jooq;
		
		@Autowired
		private TTABLE table;
		
		@Autowired
		protected ModelMapper modelMapper;
		
		/**
		 * Creates a Record(JOOQ generated) object from the Entity Type.
		 * used for persisting / updating data the jooq way.
		 * by mapping the Type -> Record
		 * 
		 * @param target Entity Class
		 * @return Record equivalent generated by JOOQ.
		 */
		public TRECORD createRecord(T entity){
			TRECORD record = null;
			record = jooq.newRecord(table,entity);
			modelMapper.map(entity, record);
			
			return record;
		}
}
